### ISSUE TITLE
使用该mod启动MC后，同时开启浏览器使用clash for windows代理访问网页导致java和clash dashboard崩溃

### ISSUE THREAD

**Issue by rtxyd** [MCTeamPotato/Rubidium-Extra-Potato-Edition#3]
java的崩溃日志如下，MC没有产生崩溃日志。当删除该mod后，该问题就无了。
版本: MC 1.16.5
MOD: magnesium_extras-mc1.16.5_v1.5.4
clash for windows: 0.15.5
microsoft edge: 111.0.1661.62
看样子是那啥multi-draw的问题。使用原版mod也会导致这个问题。效果是，MC直接闪退，浏览器卡住，clash报dash board崩溃。
[hs_err_pid8396.log](https://github.com/MCTeamPotato/Rubidium-Extra-Potato-Edition/files/11158013/hs_err_pid8396.log)

**Comment by Kasualix** [comment]
我clash天天挂老美也没崩过啊
要不你Java降一降试试，我用的azul zulu jdk 11

**Comment by Kasualix** [comment]
“原版mod”是个啥子

> 使用原版mod也会导致这个问题。

**Comment by Kasualix** [comment]
https://github.com/embeddedt/ModernFix/wiki/1.16---required-arguments-for-Java-17
或者安装ModernFix怼上这个参数试试

**Comment by Kasualix** [comment]
close as no response
